#!/usr/bin/env bash

# Variables
IMAGE_NAME=sdvx-score-rader-api
IMAGE_VERSION=1.0.0

# Push a container image
# echo $CONTAINER_REGISTRY_PASSWORD | docker login -u=$CONTAINER_REGISTRY_USERNAME --password-stdin $CONTAINER_REGISTRY_REGISTRY_URL
# docker tag $IMAGE_NAME:$IMAGE_VERSION $CONTAINER_REGISTRY_REPOSITORY_URL:$IMAGE_VERSION
# docker push $CONTAINER_REGISTRY_REPOSITORY_URL:$IMAGE_VERSION
